{% set name = "inspiral_range" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower|replace('_', '-') }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6dccea8ea373d803af3599a3a0b491b193e36e3e7571cbcdf2b1ddcb0a342dee

build:
  entry_points:
    - inspiral-range = inspiral_range.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - astropy  # [win]
    - python-lal  # [not win]
    - python-lalsimulation  # [not win]
    - python
    - scipy

test:
  imports:
    - inspiral_range
  source_files:
    - inspiral_range/test
  commands:
    - inspiral-range --asd inspiral_range/test/O2.txt
    - inspiral-range --asd inspiral_range/test/O3.txt m1=30 m2=30

about:
  home: https://git.ligo.org/gwinc/inspiral_range
  dev_url: https://git.ligo.org/gwinc/inspiral_range
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: GW detector inspiral range calculation tools
  description: |
    The inspiral_range package provides tools for calculating various binary
    inspiral range measures useful as figures of merit for gravitational wave
    detectors characterised by a strain noise spectral density.

    It includes a command-line tool for calculating various inspiral ranges
    from a supplied file of detector noise spectral density (either ASD or
    PSD).

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
