{% set name = "inspiral_range" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower|replace('_', '-') }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72faa54383e432f19640f1ccbe8f2aa9bffab1d3e583596ea91177021ea58b35
  patches:
    # remove astropy requirement on Unix, we can use lal
    - no-astropy-requirement.patch  # [not win]

build:
  entry_points:
    - inspiral-range = inspiral_range.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - astropy  # [win]
    - gpstime
    - numpy
    - python-lal  # [not win]
    - python-lalsimulation  # [not win]
    - python
    - pyyaml
    - scipy

test:
  source_files:
    # these are installed, but easier to refer to the ASD files from here
    - inspiral_range/test
  requires:
    - pip
  commands:
    # validate requirements
    - python -m pip check
    # check the cli
    - inspiral-range --asd inspiral_range/test/O2.txt
    - inspiral-range --asd inspiral_range/test/O3.txt m1=30 m2=30

about:
  home: https://git.ligo.org/gwinc/inspiral_range
  dev_url: https://git.ligo.org/gwinc/inspiral_range
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: GW detector inspiral range calculation tools
  description: |
    The inspiral_range package provides tools for calculating various binary
    inspiral range measures useful as figures of merit for gravitational wave
    detectors characterised by a strain noise spectral density.

    It includes a command-line tool for calculating various inspiral ranges
    from a supplied file of detector noise spectral density (either ASD or
    PSD).

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
